import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ART from "data/art.json";
import ArtItem from "components/ArtItem";

const Home: NextPage = () => {
  const artData = ART.data;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto w-full max-w-screen-lg">
        {/* TODO: Show the 4 pieces of art along with their details */}
        <h1>Example App</h1>
        <form>
          {/* TODO: Filter art */}
          <input type="search" placeholder="Search…" className="border" />
        </form>
        <ul className="flex flex-col gap-4 md:grid md:grid-cols-2">
          {/* TODO: List of art */}
          {artData.map((data) => (
            <ArtItem key={data.title} data={data} />
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
