import React, { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import ArtGallery from "components/ArtGallery";
import ART from "data/art.json";
import { IArt } from "utils/types";

const Home: NextPage = () => {
  const artData = ART.data;
  const [artFilter, setArtFilter] = useState("");
  const [filteredArt, setFilteredArt] = useState(artData);

  const handleFilter = (event: React.ChangeEvent<HTMLInputElement>) =>
    setArtFilter(event.target.value);

  useEffect(() => {
    setFilteredArt(
      artData.filter((art) =>
        Object.keys(art).some((property) =>
          art[property as keyof IArt]
            .toLocaleLowerCase()
            .includes(artFilter.toLocaleLowerCase())
        )
      )
    );
  }, [artData, artFilter]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto w-full max-w-screen-lg">
        {/* TODO: Show the 4 pieces of art along with their details */}
        <h1>Example App</h1>
        <section className="mb-4">
          <form>
            {/* TODO: Filter art */}
            <input
              type="search"
              placeholder="Search…"
              className="border"
              value={artFilter}
              onChange={handleFilter}
            />
          </form>
        </section>
        <ArtGallery data={filteredArt} />
      </main>
    </>
  );
};

export default Home;
